import { ethers, network } from "hardhat";
import { readFileSync, writeFileSync, existsSync, readFileSync as readEnv } from "fs";
import { resolve } from "path";

/**
 * Produce a FRESH VoteCast event on Mezo Mainnet today (without
 * waiting for next Thursday's epoch rollover) by adding a second
 * delegated user with their own veMEZO NFT.
 *
 * Why this works: BoostVoter's `onlyNewEpoch(tokenId)` is keyed on
 * tokenId, not user. The keeper EOA (tokenId 2335) already voted in
 * epoch 2942 — second attempts revert AlreadyVotedOrDeposited and
 * the Optimizer catches them as VoteSkipped. A NEW tokenId has never
 * voted, so its vote lands cleanly. The Optimizer's per-user fan-out
 * iterates BOTH users: the keeper hits VoteSkipped, the new user
 * hits VoteCast.
 *
 * Sequence (all one script, ~7 txs total, ~$1.50 in gas):
 *   1. Generate / load the demo wallet (saved to .env on first run
 *      so re-running is idempotent)
 *   2. From keeper: send 0.00003 BTC + 1.1 MEZO to demo wallet
 *   3. From demo wallet: MEZO.approve(VeMEZO, 1) + createLock(1, 1w)
 *   4. From demo wallet: VeMEZO.setApprovalForAll(adapter, true)
 *   5. From demo wallet: Optimizer.delegate(self)
 *   6. From keeper: castOptimalVote with explicit gas (now 2 users)
 *   7. Assert: VoteCast=1, VoteSkipped=1 (keeper), TickAttempted=1
 */
const MANIFEST_PATH = resolve(__dirname, "..", "deployments", "mezo-mainnet.json");
const ENV_PATH = resolve(__dirname, "..", ".env");
const DEMO_FUND_BTC = ethers.parseUnits("0.00003", 18); // ~$2.30 for the demo wallet's ops
const DEMO_LOCK_MEZO = ethers.parseUnits("1", 18); // 1 MEZO for the lock
const DEMO_SEND_MEZO = ethers.parseUnits("1.1", 18); // slight buffer over the lock
const LOCK_DURATION = 604_800n; // 1 week min

function explorer(hash: string): string {
  return `https://explorer.mezo.org/tx/${hash}`;
}

function loadOrCreateDemoWallet(): ethers.Wallet {
  // Idempotent: persist the demo wallet's private key into .env on first
  // run so re-running the script reuses it (we don't want to fund a
  // fresh wallet every run).
  let envBody = existsSync(ENV_PATH) ? readEnv(ENV_PATH, "utf8") : "";
  const existingMatch = envBody.match(/^DEMO_USER_PRIVATE_KEY=(0x[a-fA-F0-9]{64})/m);
  if (existingMatch) {
    console.log("Reusing existing DEMO_USER_PRIVATE_KEY from .env");
    return new ethers.Wallet(existingMatch[1]);
  }
  const w = ethers.Wallet.createRandom();
  envBody = envBody.trimEnd() + `\n\n# Generated by mainnet-second-user-demo.ts on ${new Date().toISOString()}\nDEMO_USER_PRIVATE_KEY=${w.privateKey}\n`;
  writeFileSync(ENV_PATH, envBody, "utf8");
  console.log(`Generated fresh demo wallet ${w.address} and saved to .env`);
  return new ethers.Wallet(w.privateKey);
}

async function main() {
  if (network.config.chainId !== 31612) {
    throw new Error(`Must run on mezoMainnet (31612). Got ${network.config.chainId}`);
  }
  const manifest = JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
  const optAddr = manifest.contracts.MezoYieldOptimizer.address as string;
  const adapterAddr = manifest.contracts.MockGaugeController.address as string;
  const veMezoAddr = manifest.external.VeMEZO as string;
  const mezoAddr = manifest.external.MEZO as string;

  const [keeper] = await ethers.getSigners();
  const demoWallet = loadOrCreateDemoWallet().connect(ethers.provider);

  console.log("═".repeat(70));
  console.log(` Mezo Mainnet second-user demo`);
  console.log("═".repeat(70));
  console.log(`Keeper EOA:    ${keeper.address}`);
  console.log(`Demo user:     ${demoWallet.address}`);
  console.log(`Optimizer:     ${optAddr}`);
  console.log(`Adapter:       ${adapterAddr}`);
  console.log("");

  const mezo = new ethers.Contract(
    mezoAddr,
    [
      "function balanceOf(address) view returns (uint256)",
      "function approve(address, uint256) returns (bool)",
      "function transfer(address, uint256) returns (bool)",
    ],
    keeper,
  );
  const veMezo = new ethers.Contract(
    veMezoAddr,
    [
      "function balanceOf(address) view returns (uint256)",
      "function ownerToNFTokenIdList(address, uint256) view returns (uint256)",
      "function isApprovedForAll(address, address) view returns (bool)",
      "function setApprovalForAll(address, bool)",
      "function createLock(uint256, uint256) returns (uint256)",
    ],
    demoWallet,
  );

  // ─── 1. Fund demo wallet ─────────────────────────────────────
  const demoBtc = await ethers.provider.getBalance(demoWallet.address);
  const demoMezo = (await mezo.balanceOf(demoWallet.address)) as bigint;
  console.log(`[1/6] Demo wallet pre-funding: ${ethers.formatEther(demoBtc)} BTC, ${ethers.formatUnits(demoMezo, 18)} MEZO`);
  if (demoBtc < DEMO_FUND_BTC) {
    const tx = await keeper.sendTransaction({ to: demoWallet.address, value: DEMO_FUND_BTC });
    console.log(`      BTC transfer: ${explorer(tx.hash)}`);
    await tx.wait();
  } else {
    console.log(`      Skip BTC transfer (already has enough)`);
  }
  if (demoMezo < DEMO_LOCK_MEZO) {
    const tx = await mezo.transfer(demoWallet.address, DEMO_SEND_MEZO);
    console.log(`      MEZO transfer: ${explorer(tx.hash)}`);
    await tx.wait();
  } else {
    console.log(`      Skip MEZO transfer (already has enough)`);
  }

  // ─── 2. createLock from demo wallet ─────────────────────────
  const nftCountBefore = (await veMezo.balanceOf(demoWallet.address)) as bigint;
  console.log(`\n[2/6] Demo wallet veMEZO NFT count: ${nftCountBefore}`);
  if (nftCountBefore === 0n) {
    const mezoFromDemo = mezo.connect(demoWallet);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const approveTx = await (mezoFromDemo as any).approve(veMezoAddr, DEMO_LOCK_MEZO);
    console.log(`      approve MEZO→VeMEZO: ${explorer(approveTx.hash)}`);
    await approveTx.wait();
    const lockTx = await veMezo.createLock(DEMO_LOCK_MEZO, LOCK_DURATION);
    console.log(`      createLock: ${explorer(lockTx.hash)}`);
    await lockTx.wait();
  }
  const nftCountAfter = (await veMezo.balanceOf(demoWallet.address)) as bigint;
  const newTokenId = (await veMezo.ownerToNFTokenIdList(demoWallet.address, 0)) as bigint;
  console.log(`      Demo NFT tokenId: ${newTokenId}`);

  // ─── 3. setApprovalForAll from demo wallet ─────────────────
  const approved = (await veMezo.isApprovedForAll(demoWallet.address, adapterAddr)) as boolean;
  console.log(`\n[3/6] Adapter approval: ${approved}`);
  if (!approved) {
    const tx = await veMezo.setApprovalForAll(adapterAddr, true);
    console.log(`      setApprovalForAll: ${explorer(tx.hash)}`);
    await tx.wait();
  }

  // ─── 4. delegate(self) from demo wallet ─────────────────────
  const optimizer = (await ethers.getContractAt("MezoYieldOptimizer", optAddr)).connect(demoWallet);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const isDelegated = await (optimizer as any).isDelegated(demoWallet.address);
  console.log(`\n[4/6] isDelegated(demo): ${isDelegated}`);
  if (!isDelegated) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const tx = await (optimizer as any).delegate(demoWallet.address);
    console.log(`      delegate: ${explorer(tx.hash)}`);
    await tx.wait();
  }

  // ─── 5. Keeper triggers castOptimalVote ─────────────────────
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const delegatedCount = (await (optimizer as any).delegatedUsersCount()) as bigint;
  console.log(`\n[5/6] delegatedUsersCount: ${delegatedCount} (should be 2)`);

  const adapter = await ethers.getContractAt("BoostVoterAdapter", adapterAddr);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const gaugesRaw = await (adapter as any).gauges();
  const voteGauges = [...gaugesRaw].slice(0, 2).map((g: string) => g);
  const voteWeights = [6000n, 4000n];
  const gas = 300_000n + 600_000n * delegatedCount;
  console.log(`      castOptimalVote: ${voteGauges.length} gauges, gas=${gas}`);
  const optimizerAsKeeper = (await ethers.getContractAt("MezoYieldOptimizer", optAddr)).connect(keeper);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const castTx = await (optimizerAsKeeper as any).castOptimalVote(voteGauges, voteWeights, { gasLimit: gas });
  console.log(`      castOptimalVote tx: ${explorer(castTx.hash)}`);
  const receipt = await castTx.wait();
  console.log(`      block: ${receipt.blockNumber}  status: ${receipt.status}`);

  // ─── 6. Decode events ──────────────────────────────────────
  const voteCastTopic = ethers.id("VoteCast(address[],uint256[])");
  const tickTopic = ethers.id("TickAttempted(uint256,uint256,uint256)");
  const skipTopic = ethers.id("VoteSkipped(address,bytes)");
  let voteCast = 0, ticks = 0, skipped: string[] = [];
  for (const l of receipt.logs as Array<{ topics: ReadonlyArray<string>; address: string }>) {
    if (l.address.toLowerCase() !== optAddr.toLowerCase()) continue;
    if (l.topics[0] === voteCastTopic) voteCast++;
    else if (l.topics[0] === tickTopic) ticks++;
    else if (l.topics[0] === skipTopic) skipped.push("0x" + l.topics[1].slice(-40));
  }
  console.log(`\n[6/6] Event tally:`);
  console.log(`      VoteCast:      ${voteCast}  ${voteCast >= 1 ? "✅ FRESH ON-CHAIN VOTE LANDED" : "❌"}`);
  console.log(`      TickAttempted: ${ticks}  ${ticks === 1 ? "✅" : "❌"}`);
  console.log(`      VoteSkipped:   ${skipped.length}  (expected: keeper's tokenId 2335 already voted this epoch)`);
  for (const u of skipped) console.log(`        skipped: ${u}`);

  console.log("\n" + "═".repeat(70));
  if (voteCast >= 1) {
    console.log(` 🎉 SUCCESS — fresh VoteCast on Mezo Mainnet via the second user`);
    console.log(`    tx: ${castTx.hash}`);
    console.log(`    The keeper's previous vote (tokenId 2335) was correctly`);
    console.log(`    rejected by BoostVoter's per-epoch guard; the NEW user's`);
    console.log(`    tokenId ${newTokenId} cast a clean vote in the same tx.`);
  } else {
    console.log(` ❌ NO VoteCast emitted — investigate VoteSkipped reasons above.`);
    process.exitCode = 1;
  }
  console.log("═".repeat(70));
}

main().catch((err) => {
  console.error("\n❌ second-user demo crashed:");
  console.error(err);
  process.exitCode = 1;
});
