import { expect } from "chai";
import { ethers } from "hardhat";
import { loadFixture } from "@nomicfoundation/hardhat-toolbox/network-helpers";

// Note: typechain-types are generated by `hardhat compile` and are useful for
// IDE intellisense, but importing them here makes tsc walk into generated
// files that depend on `ethers` types not directly resolvable from this
// package (ethers comes through hardhat-toolbox transitively). We rely on
// hardhat-ethers' runtime casts and assert behavior end-to-end instead.

/**
 * BDD coverage for STORY-003 (`context/docs/stories/story-003.md`):
 *
 *   Given a user has approved delegation to the optimizer
 *   When they call `delegate()` then `isDelegated(userAddress)` returns true
 *
 *   When they call `setManualAllocation([gaugeA, gaugeB], [6000, 4000])`
 *   Then `getAllocation(userAddress)` returns those gauges and weights
 *   And the weights sum to 10000 (basis points)
 *
 *   When a keeper calls `castOptimalVote([gaugeA, gaugeB], [7000, 3000])`
 *   Then the contract emits `VoteCast(gauges, weights)`
 *   And the weights sum to 10000
 *
 *   When weights do NOT sum to 10000 → revert "weights must sum to 10000"
 *
 *   When a non-keeper calls `castOptimalVote` → revert "not authorized"
 *
 *   When `claimRewards(userAddress)` is called
 *   Then it forwards the call to the Matchbox IMatchbox interface
 *
 * Mocks for IGaugeController/IMatchbox are testnet stand-ins; the real Mezo
 * gauge system is `mezo-org/tigris`'s Voter.sol (Solidly-style) — disclosed
 * in `TESTNET_ADDRESSES.md` and CLAUDE.md. STORY-005+ wraps real Tigris.
 */
describe("MezoYieldOptimizer", () => {
  async function deployFixture() {
    const [deployer, keeper, user, stranger, gaugeA, gaugeB, gaugeC] =
      await ethers.getSigners();

    const GaugeControllerFactory = await ethers.getContractFactory("MockGaugeController");
    // Hardhat-ethers returns a BaseContract by default; the contract methods
    // are reachable at runtime via the abi but not on the static type. We
    // could import typechain-types for a precise type, but doing so makes tsc
    // walk into generated files that depend on `ethers` types not directly
    // resolvable from this package (ethers comes through hardhat-toolbox
    // transitively). `any` here is an explicit, scoped trade — runtime tests
    // assert full behavior end-to-end including revert strings + event args.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const gaugeController: any = await GaugeControllerFactory.deploy();
    await gaugeController.waitForDeployment();

    const MatchboxFactory = await ethers.getContractFactory("MockMatchbox");
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const matchbox: any = await MatchboxFactory.deploy();
    await matchbox.waitForDeployment();

    // veMEZO eligibility gate source. Tests that need a user to delegate
    // must call `veMezo.mint(user.address, ...)` first to satisfy the
    // `balanceOf > 0` check in `delegate()`.
    const VeMezoFactory = await ethers.getContractFactory("MockVeMezo");
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const veMezo: any = await VeMezoFactory.deploy();
    await veMezo.waitForDeployment();

    const OptimizerFactory = await ethers.getContractFactory("MezoYieldOptimizer");
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const optimizer: any = await OptimizerFactory.deploy(
      await gaugeController.getAddress(),
      await matchbox.getAddress(),
      await veMezo.getAddress(),
      keeper.address,
    );
    await optimizer.waitForDeployment();

    // Convenience helper: seed all signers used as delegators with
    // 1 veMEZO so the eligibility check passes without ceremony.
    const ONE = 10n ** 18n;
    await veMezo.mint(user.address, ONE);
    await veMezo.mint(stranger.address, ONE);
    await veMezo.mint(deployer.address, ONE);

    return {
      optimizer,
      gaugeController,
      matchbox,
      veMezo,
      deployer,
      keeper,
      user,
      stranger,
      gaugeA: gaugeA.address,
      gaugeB: gaugeB.address,
      gaugeC: gaugeC.address,
    };
  }

  describe("constructor", () => {
    it("rejects zero addresses", async () => {
      const Factory = await ethers.getContractFactory("MezoYieldOptimizer");
      await expect(
        Factory.deploy(
          ethers.ZeroAddress,
          ethers.ZeroAddress,
          ethers.ZeroAddress,
          ethers.ZeroAddress,
        ),
      ).to.be.revertedWithCustomError(Factory, "ZeroAddress");
    });

    it("emits OwnerTransferred and KeeperUpdated on deploy", async () => {
      const { optimizer, deployer, keeper, veMezo } = await loadFixture(deployFixture);
      // Re-deploy to capture deployment events.
      const ControllerFactory = await ethers.getContractFactory("MockGaugeController");
      const c = await ControllerFactory.deploy();
      const MatchboxFactory = await ethers.getContractFactory("MockMatchbox");
      const m = await MatchboxFactory.deploy();
      const Factory = await ethers.getContractFactory("MezoYieldOptimizer");
      const tx = await Factory.deploy(
        await c.getAddress(),
        await m.getAddress(),
        await veMezo.getAddress(),
        keeper.address,
      );
      await expect(tx.deploymentTransaction()!)
        .to.emit(tx, "OwnerTransferred")
        .withArgs(ethers.ZeroAddress, deployer.address)
        .and.to.emit(tx, "KeeperUpdated")
        .withArgs(ethers.ZeroAddress, keeper.address);
      // Side-uses to silence the unused 'optimizer' var.
      expect(await optimizer.TOTAL_BPS()).to.equal(10_000n);
    });
  });

  describe("delegate(address)", () => {
    it("flips isDelegated to true and emits Delegated when user opts themselves in", async () => {
      const { optimizer, user } = await loadFixture(deployFixture);
      expect(await optimizer.isDelegated(user.address)).to.equal(false);
      await expect(optimizer.connect(user).delegate(user.address))
        .to.emit(optimizer, "Delegated")
        .withArgs(user.address);
      expect(await optimizer.isDelegated(user.address)).to.equal(true);
    });

    it("reverts CallerMustMatchUser when caller tries to delegate another address", async () => {
      const { optimizer, user, stranger } = await loadFixture(deployFixture);
      await expect(
        optimizer.connect(stranger).delegate(user.address),
      ).to.be.revertedWithCustomError(optimizer, "CallerMustMatchUser");
    });

    it("reverts NotEligibleToDelegate when caller holds zero veMEZO", async () => {
      // Use the fixture's `gaugeA` signer — an unfunded EOA (no veMEZO mint).
      const { optimizer } = await loadFixture(deployFixture);
      const signers = await ethers.getSigners();
      const noNftCaller = signers[4]; // gaugeA slot — not minted veMEZO in fixture
      await expect(
        optimizer.connect(noNftCaller).delegate(noNftCaller.address),
      ).to.be.revertedWithCustomError(optimizer, "NotEligibleToDelegate");
    });

    it("is idempotent — second delegate() call does not double-push or re-emit", async () => {
      const { optimizer, user } = await loadFixture(deployFixture);
      await expect(optimizer.connect(user).delegate(user.address))
        .to.emit(optimizer, "Delegated")
        .withArgs(user.address);
      // Second call: no event, no array growth.
      await expect(optimizer.connect(user).delegate(user.address)).to.not.emit(
        optimizer,
        "Delegated",
      );
      expect(await optimizer.delegatedUsersCount()).to.equal(1n);
      expect(await optimizer.delegatedUsers()).to.deep.equal([user.address]);
    });

    it("appends each new delegator to delegatedUsers() in order", async () => {
      const { optimizer, user, stranger, deployer } = await loadFixture(deployFixture);
      await optimizer.connect(user).delegate(user.address);
      await optimizer.connect(stranger).delegate(stranger.address);
      await optimizer.connect(deployer).delegate(deployer.address);
      expect(await optimizer.delegatedUsersCount()).to.equal(3n);
      expect(await optimizer.delegatedUsers()).to.deep.equal([
        user.address,
        stranger.address,
        deployer.address,
      ]);
    });
  });

  describe("setManualAllocation()", () => {
    it("stores gauges + weights when sum == 10000", async () => {
      const { optimizer, user, gaugeA, gaugeB } = await loadFixture(deployFixture);
      await expect(
        optimizer.connect(user).setManualAllocation([gaugeA, gaugeB], [6000, 4000]),
      )
        .to.emit(optimizer, "ManualAllocationSet")
        .withArgs(user.address, [gaugeA, gaugeB], [6000, 4000]);

      const [gauges, weights] = await optimizer.getAllocation(user.address);
      expect(gauges).to.deep.equal([gaugeA, gaugeB]);
      expect(weights.map((w: bigint) => Number(w))).to.deep.equal([6000, 4000]);
    });

    it("reverts with 'weights must sum to 10000' when off-target", async () => {
      const { optimizer, user, gaugeA, gaugeB } = await loadFixture(deployFixture);
      await expect(
        optimizer.connect(user).setManualAllocation([gaugeA, gaugeB], [6000, 3999]),
      ).to.be.revertedWith("weights must sum to 10000");
    });

    it("reverts on length mismatch (custom error)", async () => {
      const { optimizer, user, gaugeA, gaugeB } = await loadFixture(deployFixture);
      await expect(
        optimizer.connect(user).setManualAllocation([gaugeA, gaugeB], [10000]),
      ).to.be.revertedWithCustomError(optimizer, "LengthMismatch");
    });

    it("reverts on empty allocation (custom error)", async () => {
      const { optimizer, user } = await loadFixture(deployFixture);
      await expect(
        optimizer.connect(user).setManualAllocation([], []),
      ).to.be.revertedWithCustomError(optimizer, "EmptyAllocation");
    });
  });

  describe("castOptimalVote()", () => {
    it("fans out to gauge controller per delegated user and emits VoteCast once", async () => {
      const { optimizer, gaugeController, keeper, user, gaugeA, gaugeB } =
        await loadFixture(deployFixture);
      await optimizer.connect(user).delegate(user.address);
      await expect(
        optimizer.connect(keeper).castOptimalVote([gaugeA, gaugeB], [7000, 3000]),
      )
        .to.emit(optimizer, "VoteCast")
        .withArgs([gaugeA, gaugeB], [7000, 3000]);

      const [gauges, weights] = await gaugeController.getLastVote();
      expect(gauges).to.deep.equal([gaugeA, gaugeB]);
      expect(weights.map((w: bigint) => Number(w))).to.deep.equal([7000, 3000]);
      // lastVoter is the per-user `voter` argument, not the optimizer's
      // contract address — this is the regression test for the v1→v2
      // architectural bug that caused mainnet CallerHasNoVeMezo reverts.
      expect(await gaugeController.lastVoter()).to.equal(user.address);
      expect(await gaugeController.voteCount()).to.equal(1n);
    });

    it("iterates every delegated user in registration order", async () => {
      const { optimizer, gaugeController, keeper, user, stranger, gaugeA, gaugeB } =
        await loadFixture(deployFixture);
      await optimizer.connect(user).delegate(user.address);
      await optimizer.connect(stranger).delegate(stranger.address);

      await optimizer.connect(keeper).castOptimalVote([gaugeA, gaugeB], [6000, 4000]);

      expect(await gaugeController.voteCount()).to.equal(2n);
      // Last recorded voter is the last user iterated.
      expect(await gaugeController.lastVoter()).to.equal(stranger.address);
    });

    it("is a no-op when no users have delegated: no VoteCast, but TickAttempted still fires", async () => {
      // Two events do different jobs:
      //   - VoteCast: only on success (user-facing "real vote landed" receipt)
      //   - TickAttempted: every call, so the keeper's per-epoch dedup
      //     has a marker even when nothing landed. Codex P1 round 3.
      const { optimizer, gaugeController, keeper, gaugeA, gaugeB } =
        await loadFixture(deployFixture);
      const txPromise = optimizer
        .connect(keeper)
        .castOptimalVote([gaugeA, gaugeB], [5000, 5000]);
      await expect(txPromise).to.not.emit(optimizer, "VoteCast");
      await expect(txPromise).to.emit(optimizer, "TickAttempted");
      expect(await gaugeController.voteCount()).to.equal(0n);
    });

    it("emits TickAttempted with success/delegated counts (dedup marker)", async () => {
      const { optimizer, keeper, user, gaugeA, gaugeB } =
        await loadFixture(deployFixture);
      await optimizer.connect(user).delegate(user.address);
      const tx = await optimizer
        .connect(keeper)
        .castOptimalVote([gaugeA, gaugeB], [6000, 4000]);
      const receipt = await tx.wait();
      const topic = ethers.id("TickAttempted(uint256,uint256,uint256)");
      const logs = receipt!.logs.filter(
        (l: { topics: ReadonlyArray<string> }) => l.topics[0] === topic,
      );
      expect(logs.length).to.equal(1);
      // data = (timestamp, successCount, delegatedUserCount) — 3 uint256s
      const data = logs[0].data;
      const decoded = ethers.AbiCoder.defaultAbiCoder().decode(
        ["uint256", "uint256", "uint256"],
        data,
      );
      expect(decoded[1]).to.equal(1n); // successCount
      expect(decoded[2]).to.equal(1n); // delegatedUserCount
    });

    it("does NOT emit VoteCast when every delegated user's adapter call reverts, BUT TickAttempted does fire", async () => {
      const { optimizer, gaugeController, keeper, user, gaugeA, gaugeB } =
        await loadFixture(deployFixture);
      await optimizer.connect(user).delegate(user.address);
      await gaugeController.setShouldRevertFor(user.address, true);
      const txPromise = optimizer
        .connect(keeper)
        .castOptimalVote([gaugeA, gaugeB], [5000, 5000]);
      await expect(txPromise).to.emit(optimizer, "VoteSkipped");
      await expect(txPromise).to.emit(optimizer, "TickAttempted");
      await expect(txPromise).to.not.emit(optimizer, "VoteCast");
      expect(await gaugeController.voteCount()).to.equal(0n);
    });

    it("skips users whose adapter call reverts, continues others, emits VoteSkipped", async () => {
      const { optimizer, gaugeController, keeper, user, stranger, gaugeA, gaugeB } =
        await loadFixture(deployFixture);
      await optimizer.connect(user).delegate(user.address);
      await optimizer.connect(stranger).delegate(stranger.address);

      // Force the adapter to revert for stranger only (simulates revoked
      // approval, transferred NFT, or epoch-already-voted on mainnet).
      await gaugeController.setShouldRevertFor(stranger.address, true);

      const tx = await optimizer
        .connect(keeper)
        .castOptimalVote([gaugeA, gaugeB], [5000, 5000]);
      const receipt = await tx.wait();

      // VoteCast summary still fires.
      const voteCastLogs = receipt!.logs.filter(
        (l: { topics: ReadonlyArray<string> }) =>
          l.topics[0] === ethers.id("VoteCast(address[],uint256[])"),
      );
      expect(voteCastLogs.length).to.equal(1);

      // Exactly one VoteSkipped, for stranger (indexed first topic).
      const voteSkippedTopic = ethers.id("VoteSkipped(address,bytes)");
      const skippedLogs = receipt!.logs.filter(
        (l: { topics: ReadonlyArray<string> }) => l.topics[0] === voteSkippedTopic,
      );
      expect(skippedLogs.length).to.equal(1);
      // topics[1] is the indexed user address, padded to 32 bytes.
      expect("0x" + skippedLogs[0].topics[1].slice(-40)).to.equal(
        stranger.address.toLowerCase(),
      );

      // user voted, stranger was skipped → voteCount = 1.
      expect(await gaugeController.voteCount()).to.equal(1n);
      expect(await gaugeController.lastVoter()).to.equal(user.address);
    });

    it("permits the owner (deployer) to act as a keeper", async () => {
      const { optimizer, deployer, user, gaugeA, gaugeB } = await loadFixture(deployFixture);
      await optimizer.connect(user).delegate(user.address);
      await expect(
        optimizer.connect(deployer).castOptimalVote([gaugeA, gaugeB], [5000, 5000]),
      ).to.emit(optimizer, "VoteCast");
    });

    it("reverts with 'not authorized' for non-keeper, non-owner caller", async () => {
      const { optimizer, stranger, gaugeA, gaugeB } = await loadFixture(deployFixture);
      await expect(
        optimizer.connect(stranger).castOptimalVote([gaugeA, gaugeB], [5000, 5000]),
      ).to.be.revertedWith("not authorized");
    });

    it("reverts with 'weights must sum to 10000' when sum is wrong", async () => {
      const { optimizer, keeper, gaugeA, gaugeB } = await loadFixture(deployFixture);
      await expect(
        optimizer.connect(keeper).castOptimalVote([gaugeA, gaugeB], [5000, 4999]),
      ).to.be.revertedWith("weights must sum to 10000");
    });
  });

  describe("claimRewards()", () => {
    it("forwards to Matchbox.claim and emits RewardsClaimed with the returned amount", async () => {
      const { optimizer, matchbox, user } = await loadFixture(deployFixture);
      const pending = ethers.parseUnits("12.4", 18);
      await matchbox.setPending(user.address, pending);

      await expect(optimizer.claimRewards(user.address))
        .to.emit(optimizer, "RewardsClaimed")
        .withArgs(user.address, pending)
        .and.to.emit(matchbox, "Claimed")
        .withArgs(user.address, pending);

      expect(await matchbox.pending(user.address)).to.equal(0n);
    });

    it("returns the claimed amount via staticCall (used by STORY-008 useSimulateContract)", async () => {
      const { optimizer, matchbox, user } = await loadFixture(deployFixture);
      const pending = ethers.parseUnits("3.5", 18);
      await matchbox.setPending(user.address, pending);

      const simulated = await optimizer.claimRewards.staticCall(user.address);
      expect(simulated).to.equal(pending);

      // staticCall doesn't actually mutate, so pending is untouched.
      expect(await matchbox.pending(user.address)).to.equal(pending);
    });
  });

  describe("setKeeper()", () => {
    it("rotates the keeper when called by owner", async () => {
      const { optimizer, deployer, keeper, stranger } = await loadFixture(deployFixture);
      await expect(optimizer.connect(deployer).setKeeper(stranger.address))
        .to.emit(optimizer, "KeeperUpdated")
        .withArgs(keeper.address, stranger.address);
      expect(await optimizer.keeper()).to.equal(stranger.address);
    });

    it("reverts with 'not owner' for non-owner caller", async () => {
      const { optimizer, stranger } = await loadFixture(deployFixture);
      await expect(optimizer.connect(stranger).setKeeper(stranger.address)).to.be.revertedWith(
        "not owner",
      );
    });

    it("rejects zero address", async () => {
      const { optimizer, deployer } = await loadFixture(deployFixture);
      await expect(
        optimizer.connect(deployer).setKeeper(ethers.ZeroAddress),
      ).to.be.revertedWithCustomError(optimizer, "ZeroAddress");
    });
  });

  describe("transferOwnership()", () => {
    it("transfers and emits", async () => {
      const { optimizer, deployer, stranger } = await loadFixture(deployFixture);
      await expect(optimizer.connect(deployer).transferOwnership(stranger.address))
        .to.emit(optimizer, "OwnerTransferred")
        .withArgs(deployer.address, stranger.address);
      expect(await optimizer.owner()).to.equal(stranger.address);
    });

    it("reverts for non-owner", async () => {
      const { optimizer, stranger } = await loadFixture(deployFixture);
      await expect(
        optimizer.connect(stranger).transferOwnership(stranger.address),
      ).to.be.revertedWith("not owner");
    });
  });
});
